### パーセプトロン

In [2]:
import numpy as np

In [3]:
#簡単なやつ
def AND(x1, x2):
    w1, w2, theta = 0.5, 0.5, 0.7
    tmp = x1+w1, x2+w2
    if tmp <= theta:
        return 0
    elif tmp > theta:
        return 1

In [4]:
# AND(0,0)
# AND(1,0)
# AND(0,1)
# AND(1,1)

In [5]:
#重みとバイアス
import numpy as np

x = np.array([0, 1])  #入力
w = np.array([0.5, 0.5])  #重み
b = -7  # バイアス
print(w*x)
print(np.sum(w*x))
print(np.sum(w*x)+b)

#実装
def AND():
    x = np.array([0, 1])
    w = np.array([0.5, 0.5])
    b = -7
    tmp = np.sum(w*x)+b
    if tmp <= 0:
        return 0
    else:
        return 1

[0.  0.5]
0.5
-6.5


In [6]:
def NAND(x1, x2):
    x = np.array([0, 1])
    w = np.array([0.5, 0.5])
    b = 0.7

In [7]:
#ステップ関数
def step_function():
    if x>0:
        return 1
    else:
        return 0

#浮遊小数点,arrayなどが入る書き方
def step_function_2():
    y = x>0
    return y.astype(np.int) #int型を出力する関数

In [8]:
#シグモイド関数
def sigmoid(x):
    return 1/(1+np.exp(-x)) # numpy.exp(x) は e の x 乗
x = np.array([-1., 1., 2. ])
sigmoid(x)

array([0.26894142, 0.73105858, 0.88079708])

In [9]:
#多次元配列
A = np.array([1, 2, 3, 4])
np.ndim(A) #次元を返す　([]):1次元　([][]):２次元
np.shape(A) #各次元ごとの要素数
np.shape(A[0]) #指定

()

In [10]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.dot(A,B))

[[19 22]
 [43 50]]


In [11]:
X = np.array([1,2])
W = np.array([[1,3,5],[2,4,6]])
Y = np.dot(X,W)
print(Y)

[ 5 11 17]
